parameters:
#  Paramètre ticket et commande
  ageMaxEnfant: 12
  ageMaxGratuit: 3
  ageMinSenior: 60
  tarifReduit: 10
  tarifEnfant: 8
  tarifNormal: 16
  tarifSenior: 12
  nbTicketsMaxJour: 1000
  heureDebDemiJournee: 14