home:
    path:   /
    defaults: { _controller: FCReservationBundle:Reserve:index }

info-tarif:
    path:   /info-tarif
    defaults: { _controller: FCReservationBundle:Reserve:infoTarif }

info-global:
    path:   /info-global
    defaults: { _controller: FCReservationBundle:Reserve:infoGlobal }

info-visite:
    path:   /info-visite
    defaults: { _controller: FCReservationBundle:Reserve:infoVisite }

info-ticket:
    path:   /info-ticket
    defaults: { _controller: FCReservationBundle:Reserve:infoTicket}

recap-commande:
    path:   /recap-commande
    defaults: { _controller: FCReservationBundle:Reserve:recapCommande}

payment:
    path:   /payment
    defaults: { _controller: FCReservationBundle:Payment:payment}

fin-commande:
    path:   /fin-commande
    defaults: { _controller: FCReservationBundle:Reserve:finCommande }