home:
    path:   /
    defaults: { _controller: FCReservationBundle:Reserve:index }

info-visite:
    path:   /info-visite
    defaults: { _controller: FCReservationBundle:Reserve:infoVisite }

info-billet:
    path:   /info-billet
    defaults: { _controller: FCReservationBundle:Reserve:infoBillet}