home:
    path:   /
    defaults: { _controller: FCReservationBundle:Reserve:index }

info-visite:
    path:   /info-visite
    defaults: { _controller: FCReservationBundle:Reserve:infoVisite }

info-ticket:
    path:   /info-ticket
    defaults: { _controller: FCReservationBundle:Reserve:infoTicket}

recap-commande:
    path:   /recap-commande
    defaults: { _controller: FCReservationBundle:Reserve:recapCommande}