services:
  fc_reserve.servtickets:
    class: FC\ReservationBundle\Services\ServTickets\FCServTickets

  fc_reserve.servcommande:
    class: FC\ReservationBundle\Services\ServCommande\FCServCommande
    arguments:
      - '@session'
      - '@fc_reserve.servtickets'
