services:
  fc_reserve.servtickets:
    class: FC\ReservationBundle\Services\ServTickets\FCServTickets
    arguments:
      - '%ageMaxEnfant%'
      - '%ageMaxGratuit%'
      - '%ageMinSenior%'
      - '%tarifReduit%'
      - '%tarifEnfant%'
      - '%tarifNormal%'
      - '%tarifSenior%'

  fc_reserve.servcommande:
    class: FC\ReservationBundle\Services\ServCommande\FCServCommande
    arguments:
      - '@session'
      - "@doctrine.orm.entity_manager"
      - '@fc_reserve.servtickets'
      - '%nbTicketsMaxJour%'
      - '%heureDebDemiJournee%'

  fc_reserve.servstripe:
    class: FC\ReservationBundle\Services\ServStripe\FCServStripe
    arguments:
      - '@fc_reserve.servcommande'
      - '@session'
      - '%stripe_secret_key%'