services:
  fc_reserve.servtickets:
    class: FC\ReservationBundle\Services\ServTickets\FCServTickets

  fc_reserve.servcommande:
    class: FC\ReservationBundle\Services\ServCommande\FCServCommande
    arguments:
      - '@session'
      - '@fc_reserve.servtickets'
      - '@doctrine.orm.entity_manager'

  fc_reserve.servstripe:
    class: FC\ReservationBundle\Services\ServStripe\FCServStripe
    arguments:
      - '@fc_reserve.servcommande'
      - '@session'
      - '%stripe_secret_key%'