<?php

namespace FC\ReservationBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbTickets($dateVisite){
        $query = $this->createQueryBuilder('a')
            ->where('a.dateVisite = :dateVisite')
            ->setParameter('dateVisite', $dateVisite)
            ->select('SUM(a.nbTicket) as nbTicketTotal')
            ->getQuery();

//        return $query->getResult();
        $nbTicketTotal = $query->getResult()[0]['nbTicketTotal'];
        return $nbTicketTotal;
    }
}
